### Register user
POST http://localhost:8080/v1/users/register
Content-Type: application/json

{
  "name": "Sergei",
  "email": "sergei@example.com",
  "password": "password123"
}

### Login user
POST http://localhost:8080/v1/users/login
Content-Type: application/json

{
  "email": "sergei@example.com",
  "password": "password123"
}

### Make reservation
@token = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlMGI3YTE0OC00OTVhLTRkYzEtOGJlNy01NmFkMjg3YmViNjAiLCJlbWFpbCI6InNlcmdlaUBleGFtcGxlLmNvbSIsImlhdCI6MTc0Nzc3OTgxOSwiZXhwIjoxNzQ3NzgzNDE5fQ.ypzqaAZTjTuDK_TyDjIgm5MRmaKUnWG2Gb1ZfRTysFQ'
POST http://localhost:8080/v1/reservations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "vehicleId": "vehicle123",
  "startTime": "2025-05-21T01:00:00Z",
  "endTime": "2025-05-21T01:12:30Z",
  "startLatitude": 59.4370,
  "startLongitude": 24.7536,
  "endLatitude": 59.4380,
  "endLongitude": 24.7550
}
