// Comment by Sergei Eensalu: Firebase error generated by AI. Not sure are they fully correct or not
// Probably if project is larger -> errors can be categorized and split by files:
// errorMessages, customErrorMessages, firebaseErrorMessages or whatever

export const errorMessages: Record<string, string> = {
  // Firebase
  'auth/user-not-found': 'User not found.',
  'auth/wrong-password': 'Incorrect password.',
  'auth/email-already-in-use': 'Email already in use.',
  'auth/invalid-email': 'Invalid email address.',
  'auth/network-request-failed': 'Network error. Please check your connection.',
  'auth/too-many-requests': 'Too many requests. Try again later.',

  // Custom
  'MAX_PAIRED_USERS_EXCEEDED': 'Scooter already paired with maximum users.',
  'INVALID_SCOOTER_CODE': 'Invalid scooter code.',

  // Fallback
  'UNKNOWN': 'Something went wrong. Please try again.',
};
